In [1]:
import sys
import pandas as pd

from IPython.display import display

sys.path.append("../../")

from helpers.save import results
from helpers.constants import BASE_GENRES

In [2]:
save = results('new_rich_results.json')
df = save.unnestDataframeLevel(level = 2)

Get top 5 models with highest f1 score per genre in test

In [8]:
for genre in BASE_GENRES:
    columnName = f"result.{genre}.f1-score"

    test = df[df['phase'] == 'test']

    top5 = test.nlargest(5, columnName)
    top5model = top5[['model', 'dataset', 'phase', columnName]].rename(columns={columnName: 'f1_score'})

    print(f'\nFor genre {genre}\n')
    display(top5model)

For genre genre_blues

               model                        dataset phase  f1_score
123    XGBClassifier       dataset_07_pvtt_mean_cov  test  0.442748
125    XGBClassifier      dataset_08_pvtt_mean_icov  test  0.430769
109    XGBClassifier                 dataset_00_all  test  0.418605
127    XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.394161
131  XGBRFClassifier                 dataset_00_all  test  0.365217

For genre genre_classical

                      model                        dataset phase  f1_score
45                      SVC                 dataset_00_all  test  0.869129
17       LogisticRegression  dataset_09_pvtt_mean_cov_icov  test  0.867515
13       LogisticRegression       dataset_07_pvtt_mean_cov  test  0.864814
43       LogisticRegression                 dataset_00_all  test  0.861203
105  RandomForestClassifier  dataset_09_pvtt_mean_cov_icov  test  0.860056

For genre genre_country

               model                        dataset phase  f1_score
109    XGBClassifier                 dataset_00_all  test  0.657143
127    XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.629371
131  XGBRFClassifier                 dataset_00_all  test  0.623188
115    XGBClassifier           dataset_03_mean_icov  test  0.594595
45               SVC                 dataset_00_all  test  0.586957

For genre genre_disco

               model                        dataset phase  f1_score
131  XGBRFClassifier                 dataset_00_all  test  0.733333
109    XGBClassifier                 dataset_00_all  test  0.700730
123    XGBClassifier       dataset_07_pvtt_mean_cov  test  0.628931
127    XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.601307
149  XGBRFClassifier  dataset_09_pvtt_mean_cov_icov  test  0.578947

For genre genre_hiphop

                      model         dataset phase  f1_score
45                      SVC  dataset_00_all  test  0.739224
43       LogisticRegression  dataset_00_all  test  0.697460
87   RandomForestClassifier  dataset_00_all  test  0.680488
109           XGBClassifier  dataset_00_all  test  0.638298
131         XGBRFClassifier  dataset_00_all  test  0.602941

For genre genre_jazz

                  model                        dataset phase  f1_score
45                  SVC                 dataset_00_all  test  0.640483
127       XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.589928
43   LogisticRegression                 dataset_00_all  test  0.583832
109       XGBClassifier                 dataset_00_all  test  0.565517
131     XGBRFClassifier                 dataset_00_all  test  0.541667

For genre genre_metal

               model                        dataset phase  f1_score
113    XGBClassifier            dataset_02_mean_cov  test  0.724832
109    XGBClassifier                 dataset_00_all  test  0.721805
127    XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.713287
149  XGBRFClassifier  dataset_09_pvtt_mean_cov_icov  test  0.697368
45               SVC                 dataset_00_all  test  0.697051

For genre genre_pop

                      model                        dataset phase  f1_score
87   RandomForestClassifier                 dataset_00_all  test  0.611090
45                      SVC                 dataset_00_all  test  0.601881
43       LogisticRegression                 dataset_00_all  test  0.579477
21     KNeighborsClassifier                 dataset_00_all  test  0.576129
105  RandomForestClassifier  dataset_09_pvtt_mean_cov_icov  test  0.555438

For genre genre_reggae

               model                        dataset phase  f1_score
109    XGBClassifier                 dataset_00_all  test  0.732026
127    XGBClassifier  dataset_09_pvtt_mean_cov_icov  test  0.675676
123    XGBClassifier       dataset_07_pvtt_mean_cov  test  0.666667
45               SVC                 dataset_00_all  test  0.665049
131  XGBRFClassifier                 dataset_00_all  test  0.645570

For genre genre_rock

                     model                        dataset phase  f1_score
45                     SVC                 dataset_00_all  test  0.650138
43      LogisticRegression                 dataset_00_all  test  0.635728
87  RandomForestClassifier                 dataset_00_all  test  0.625790
21    KNeighborsClassifier                 dataset_00_all  test  0.618160
17      LogisticRegression  dataset_09_pvtt_mean_cov_icov  test  0.603849

I wonder if we can build a regression based on multiple models...namely SVC, XGBClassifier, RandomForestClassifier, and XGBRFClassifier as one dense layer