In [15]:
import sys

import numpy as np
import pandas as pd

sys.path.append("../../")

from helpers.split import tag_label_feature_split, label_strings
from sklearn.model_selection import train_test_split

df = pd.read_pickle("../../datasets/baseline_dataset.pickle")
_, one_hot_labels, X = tag_label_feature_split(df)
y=label_strings(one_hot_labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10, stratify=y)

In [4]:
X_train

,mfcc_mean_0,mfcc_mean_1,mfcc_mean_2,mfcc_mean_3,mfcc_mean_4,mfcc_mean_5,mfcc_mean_6,mfcc_mean_7,mfcc_mean_8,mfcc_mean_9,mfcc_mean_10,mfcc_mean_11,mfcc_mean_12
15396,-638.702637,45.956467,8.659735,35.121376,6.057689,6.320784,5.488910,7.321218,-0.908293,2.995408,2.070262,3.322304,2.278360
2800,-707.048462,184.128250,2.634118,39.482048,5.222976,-2.255682,-5.270024,1.606527,0.089804,4.273519,2.380932,0.229251,1.946201
50730,-713.236145,137.153214,3.153852,24.379440,11.792075,5.817113,-8.786176,-12.456314,-6.399297,-0.411793,4.818072,4.316155,-0.090285
45568,-724.352051,135.779007,-66.909698,52.215511,0.372407,10.892290,0.495015,19.923069,22.651491,0.210138,-12.428018,-14.127147,-6.060269
46319,-682.618347,89.017860,-6.596547,10.385729,6.208825,-4.461657,-0.743637,0.110542,-0.963677,11.710200,11.369055,11.447063,7.069188
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35610,-719.250854,163.468643,39.043694,26.947054,-1.801544,-4.083395,-1.728375,-1.428022,-0.098015,-2.409420,0.750539,0.928818,-4.033556
52229,-722.144043,173.813293,-43.376671,17.851480,-12.436485,-8.144847,-6.701680,-14.471769,-4.333413,-2.835711,-14.086497,-4.672439,-12.191923
5977,-623.426514,97.246452,5.337657,42.662083,-1.123227,10.158881,3.111129,1.496940,2.981712,1.869332,-0.261474,0.491895,-2.789029
34416,-654.009155,123.005280,-21.695030,6.350929,-8.856838,-1.326946,-9.267198,-0.355875,-6.945352,-0.197057,-3.596429,0.436368,-0.577031
37276,-657.580688,67.883064,14.779691,24.537516,2.951974,13.801885,10.330754,10.430058,8.425387,7.752916,6.220369,3.762154,3.049500

In [5]:
X_test

,mfcc_mean_0,mfcc_mean_1,mfcc_mean_2,mfcc_mean_3,mfcc_mean_4,mfcc_mean_5,mfcc_mean_6,mfcc_mean_7,mfcc_mean_8,mfcc_mean_9,mfcc_mean_10,mfcc_mean_11,mfcc_mean_12
22553,-743.199219,163.423706,24.481915,48.399662,3.042211,2.282792,2.564776,-3.047920,-2.965357,-0.674616,-7.454997,2.042854,1.773150
47272,-687.400146,115.526688,32.697426,28.394089,12.014104,-2.028277,-1.016402,-2.216788,-1.307638,0.873208,-3.156199,0.478071,-3.701701
42863,-872.746643,249.562561,41.682724,-35.691261,-20.409882,-13.475871,-17.051554,-12.946568,-7.745583,-6.271906,-6.966652,-7.247458,-5.291193
38619,-688.230408,140.863052,-37.917831,16.075670,18.802238,-21.094666,-11.453188,1.319817,4.632545,-3.515749,1.127309,-3.351457,-8.849027
7668,-936.879822,200.200760,54.187710,-15.742504,-21.964525,-19.792290,-20.804632,-23.790768,-26.260479,-21.583712,-11.634739,-3.645931,-0.114480
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50687,-770.239319,130.182037,11.614623,5.269050,-6.161116,-4.491606,-16.759596,-7.319714,-5.266054,-6.208311,-15.141441,-14.358304,-7.749444
3964,-890.415955,206.413498,5.108215,-30.147518,-8.183643,-16.011751,-23.369280,-19.384670,-12.806593,-7.078889,-3.694966,-3.623387,-7.828022
34846,-654.513550,124.316444,-3.446565,13.179015,2.403157,-5.397882,-1.035713,-2.960090,-2.400337,0.458922,-6.058254,-6.604429,-1.479796
52635,-825.077820,213.515274,-20.880566,-23.208282,-45.661175,-31.886156,-2.513370,-12.919398,-12.217919,-17.781107,-22.226280,-21.436977,-19.279703
1537,-774.526062,198.039856,4.019855,1.401062,-2.626109,-10.579274,-10.111918,-3.430646,-8.147173,-2.561462,-2.156931,4.266091,10.783536

In [9]:
y_train

              label
15396   genre_metal
2800    genre_blues
50730     genre_pop
45568    genre_rock
46319  genre_hiphop
...             ...
35610     genre_pop
52229    genre_rock
5977    genre_blues
34416  genre_hiphop
37276   genre_disco

[17080 rows x 1 columns]

In [10]:
y_test

                 label
22553       genre_rock
47272        genre_pop
42863  genre_classical
38619       genre_rock
7668        genre_jazz
...                ...
50687      genre_metal
3964   genre_classical
34846        genre_pop
52635        genre_pop
1537   genre_classical

[4271 rows x 1 columns]

In [11]:
len(y_train)/len(y_test)

3.999063451182393

In [12]:
y.value_counts()/len(y)

label
genre_pop          0.250246
genre_classical    0.247108
genre_rock         0.187345
genre_hiphop       0.099574
genre_jazz         0.072690
genre_reggae       0.046134
genre_metal        0.038921
genre_blues        0.021919
genre_country      0.019156
genre_disco        0.016908
dtype: float64

In [7]:
y_train.value_counts()/len(y_train)

label
genre_pop          0.250234
genre_classical    0.247131
genre_rock         0.187354
genre_hiphop       0.099590
genre_jazz         0.072658
genre_reggae       0.046136
genre_metal        0.038934
genre_blues        0.021897
genre_country      0.019145
genre_disco        0.016920
dtype: float64

In [8]:
y_test.value_counts()/len(y_test)

label
genre_pop          0.250293
genre_classical    0.247015
genre_rock         0.187310
genre_hiphop       0.099508
genre_jazz         0.072817
genre_reggae       0.046125
genre_metal        0.038867
genre_blues        0.022009
genre_country      0.019199
genre_disco        0.016858
dtype: float64